org.gradle.jvmargs=-Xmx1536M -XX:MaxMetaspaceSize=512M -Djava.net.preferIPv4Stack=true
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.daemon.idletimeout=120000
android.useAndroidX=true
android.enableJetifier=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
kotlin.incremental=false
kotlin.daemon.jvmargs=-Xmx1024M -XX:-UseParallelGC
