name: Deploy iOS

on:
  workflow_dispatch:
    inputs:
      upload_to_testflight:
        description: "Deploy to Apple TestFlight"
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  deploy:
    uses: exa31/github-workflows/.github/workflows/flutter-ios.yml@main
    with:
      app_name: cyber-mobile
      flutter_version: "3.x"
      enable_semantic_release: false
      update_pubspec: false
      upload_to_testflight: ${{ inputs.upload_to_testflight || false }}
      env_content: |
        BASE_URL=${{ vars.BASE_URL || 'https://be-apple-store.eka-dev.cloud' }}
        GOOGLE_CLIENT_ID=${{ vars.GOOGLE_CLIENT_ID || '897905079551-0bm5skv53tbcpqobtlkaatmfheftthc4.apps.googleusercontent.com' }}
        GOOGLE_IOS_CLIENT_ID=${{ vars.GOOGLE_IOS_CLIENT_ID || '897905079551-cij7kf0fpf5smbejqthd8l488alv6siv.apps.googleusercontent.com' }}
        GOOGLE_SERVER_CLIENT_ID=${{ vars.GOOGLE_SERVER_CLIENT_ID || '897905079551-0bm5skv53tbcpqobtlkaatmfheftthc4.apps.googleusercontent.com' }}
        LOKI_URL=${{ vars.LOKI_URL || 'https://loki.eka-dev.cloud/loki/api/v1/push' }}
    secrets:
      ENV_FILE: ${{ secrets.ENV_FILE }}
      APPLE_CERTIFICATE_BASE64: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
      APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      APPLE_PROVISIONING_PROFILE_BASE64: ${{ secrets.APPLE_PROVISIONING_PROFILE_BASE64 }}
      APP_STORE_CONNECT_API_KEY_BASE64: ${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}
      APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
