name: Deploy Android

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_type:
        description: "Build Output (appbundle, apk, or both)"
        required: false
        default: "both"
        type: choice
        options:
          - appbundle
          - apk
          - both
      upload_to_play_store:
        description: "Deploy to Google Play Console"
        required: false
        default: false
        type: boolean
      track:
        description: "Google Play Track"
        required: false
        default: "internal"
        type: choice
        options:
          - internal
          - alpha
          - beta
          - production

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  deploy:
    uses: exa31/github-workflows/.github/workflows/flutter-android.yml@main
    with:
      app_name: cyber-mobile
      flutter_version: "3.x"
      java_version: "17"
      build_type: ${{ inputs.build_type || 'both' }}
      package_name: "com.cyber.cyber"
      enable_semantic_release: false
      update_pubspec: false
      upload_to_play_store: ${{ inputs.upload_to_play_store || false }}
      track: ${{ inputs.track || 'internal' }}
      env_content: |
        BASE_URL=${{ vars.BASE_URL || 'https://be-apple-store.eka-dev.cloud' }}
        GOOGLE_CLIENT_ID=${{ vars.GOOGLE_CLIENT_ID || '897905079551-0bm5skv53tbcpqobtlkaatmfheftthc4.apps.googleusercontent.com' }}
        GOOGLE_IOS_CLIENT_ID=${{ vars.GOOGLE_IOS_CLIENT_ID || '897905079551-cij7kf0fpf5smbejqthd8l488alv6siv.apps.googleusercontent.com' }}
        GOOGLE_SERVER_CLIENT_ID=${{ vars.GOOGLE_SERVER_CLIENT_ID || '897905079551-0bm5skv53tbcpqobtlkaatmfheftthc4.apps.googleusercontent.com' }}
        LOKI_URL=${{ vars.LOKI_URL || 'https://loki.eka-dev.cloud/loki/api/v1/push' }}
    secrets:
      ENV_FILE: ${{ secrets.ENV_FILE }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      PLAY_STORE_SERVICE_ACCOUNT_JSON: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}
